# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Read Properties info
      id: info
      uses: christian-draeger/read-properties@1.1.1
      with:
        path: pom.xml
        properties: 'version'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "luohyp-${{ steps.info.outputs.version }}"
        path: build/libs/*.jar
